version: '3.8'

services:
  app:
    container_name: app
    working_dir: /app
    build: .
    networks:
      - frontend
    volumes:
      - ./src:/app/src
    user: node:node
    ports:
      - 3000:3000
    logging:
      driver: 'json-file'
      options:
        max-size: '10m'
        max-file: '5'
    command: npm run dev
    restart: always

networks:
  frontend:
    name: frontend
    driver: bridge
