name: CI
run-name: Deploy
on:
  push:
    branches: [ "main" ]

  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    environment: Deploy
    steps:
      - name: Checkout the current branch
        uses: actions/checkout@v3

      - shell: bash
        env:
          GFTOKEN: ${{ secrets.gfToken }}
        run: |
          echo -e "const gfToken = 'secret'\nexport { gfToken }" > ./src/data/getform.js
          sed -i -e "s|secret|$GFTOKEN|" ./src/data/getform.js

      - name: Initialize the ssh-agent
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Scan the host key
        env:
          DEPLOY_PORT: ${{ secrets.DEPLOY_PORT }}
          DEPLOY_SERVER: ${{ secrets.DEPLOY_SERVER }}
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -p $DEPLOY_PORT -H $DEPLOY_SERVER >> ~/.ssh/known_hosts

      - name: Build
        uses: actions/setup-node@v3
        with:
          node-version: latest
          cache: "npm"
      - run: npm ci
      - run: npm run build

      - name: Deploy
        env:
          DEPLOY_PORT: ${{ secrets.DEPLOY_PORT }}
          DEPLOY_USERNAME: ${{ secrets.DEPLOY_USERNAME }}
          DEPLOY_SERVER: ${{ secrets.DEPLOY_SERVER }}
        run: rsync -avxe "ssh -p $DEPLOY_PORT -i ~/.ssh/$DEPLOY_USERNAME" --delete --exclude ".ssh" dist/ $DEPLOY_USERNAME@$DEPLOY_SERVER:./

